[General]
allow-wifi-access = false
wifi-access-http-port = 6152
wifi-access-socks5-port = 6153
http-listen = 127.0.0.1:6152
socks5-listen = 127.0.0.1:6153
allow-hotspot-access = false
skip-proxy = 127.0.0.1,192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,100.64.0.0/10,17.0.0.0/8,localhost,*.local
test-timeout = 5
proxy-test-url = http://cp.cloudflare.com/generate_204
internet-test-url = http://www.apple.com/library/test/success.html
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb
ipv6 = false
show-error-page-for-reject = true
dns-server = 119.29.29.29, 180.184.1.1, 223.5.5.5, system
encrypted-dns-server = https://223.5.5.5/dns-query
exclude-simple-hostnames = true
read-etc-hosts = true
udp-policy-not-supported-behaviour = REJECT
hide-vpn-icon = false

[Replica]
hide-apple-request = true
hide-crashlytics-request = true
use-keyword-filter = false
hide-udp = false

[Proxy]
DIRECT = direct
{{NODES}}

[Proxy Group]
⚡ 自动选择 = url-test, {{NODE_NAMES}}, url=http://www.gstatic.com/generate_204, interval=300
🚀 节点选择 = select, DIRECT, REJECT-DROP, ⚡ 自动选择, {{NODE_NAMES}}
🏠 私有网络 = select, DIRECT, 🚀 节点选择
🔒 国内服务 = select, DIRECT, 🚀 节点选择
🌐 非中国 = select, 🚀 节点选择, ⚡ 自动选择, DIRECT
🐟 漏网之鱼 = select, 🚀 节点选择, ⚡ 自动选择, DIRECT, REJECT-DROP

[Rule]
# Category: private
RULE-SET,LAN,🏠 私有网络
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Lan/Lan.list,🏠 私有网络,update-interval=86400

# Category: china-direct
RULE-SET,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list,🔒 国内服务,update-interval=86400
RULE-SET,https://raw.githubusercontent.com/chenyk1219/surge/release/ChinaDomain.list,🔒 国内服务,update-interval=86400
GEOIP,CN,🔒 国内服务

# Category: non-china
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Proxy/Proxy_All_No_Resolve.list,🌐 非中国,update-interval=86400

FINAL,🐟 漏网之鱼,dns-failed

[URL Rewrite]
^https?://(www.)?g.cn https://www.google.com 302
^https?://(www.)?google.cn https://www.google.com 302

[MITM]
